apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin-deployment
spec:
  selector:
    matchLabels:
      app: pgadmin-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: pgadmin-deployment
    spec:
      containers:
        - name: pgadmin
          image: dpage/pgadmin4:latest  # Siempre usas la etiqueta latest para obtener la última versión
          envFrom:
            - secretRef:
                name: pgadmin-secret
          ports:
            - containerPort: 80
              name: pgadminport
