#object that store enviroments variables that could be have sensitive data like a password
apiVersion: v1
kind: Secret
metadata:
  name: pgadmin-secret
  labels:
    app: pgadmin-secret
    #meant that we can use arbitrary key pair values
type: Opaque
# Indica que los datos almacenados en este Secret son arbitrarios y no están asociados a un tipo específico (por ejemplo, certificados o claves de Docker).
data:
  PGADMIN_DEFAULT_EMAIL: YWRtaW5AYWRtaW4uY29t
  # Dirección de correo predeterminada para pgAdmin codificada en Base64. Valor original: `admin@admin.com`.
  PGADMIN_DEFAULT_PASSWORD: cXdlcnR5
  # Contraseña predeterminada para pgAdmin codificada en Base64. Valor original: `qwerty`.
  PGADMIN_PORT: ODA=
  # Puerto en el que se ejecutará pgAdmin codificado en Base64. Valor original: `80`.