apiVersion: v1
# La versión de la API utilizada para este recurso.

kind: Secret
# Tipo de recurso. Un `Secret` almacena información sensible de forma segura.

metadata:
  name: postgres-secret-desarrollo
  # Nombre del Secret que será usado por los pods para referenciar este recurso.
  labels:
    app: postgres-secret-desarrollo
    # Etiquetas para organizar y clasificar el Secret.

type: Opaque
# Tipo de Secret. `Opaque` permite almacenar cualquier par clave-valor sin una estructura predeterminada.

data:
  POSTGRES_DB: cHJveWVjdG8=
  # Base de datos para PostgreSQL, codificada en base64. La cadena `cHJveWVjdG8=` es la codificación base64 de "proyecto".
  
  POSTGRES_USER: YWRtaW4=
  # Usuario de PostgreSQL, codificado en base64. La cadena `YWRtaW4=` es la codificación base64 de "admin".
  
  POSTGRES_PASSWORD: YWRtaW4=
  # Contraseña de PostgreSQL, codificada en base64. La cadena `YWRtaW4=` es la codificación base64 de "admin".


