apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-nestjs-security
  labels:
    app: ms-nestjs-security
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-nestjs-security
  template:
    metadata:
      labels:
        app: ms-nestjs-security
    spec:
      containers:
      - name: ms-nestjs-security
        #image: ms-nestjs-security-desarrollo-devops:latest  #antigua imagen que he estado utilizando primeras pruebas de jenkins 
        image: devars96/jenkins:ms-nestjs-security-desarrollo-devops
        imagePullPolicy: Never
        #imagePullPolicy: Always
        ports:
        - containerPort: 3001
        env:
        - name: ENTORNO_ENV
          value: "desarrollo"
