apiVersion: v1
kind: Service
metadata:
  name: ms-nestjs-security
spec:
  selector:
    app: ms-nestjs-security
  ports:
  - protocol: TCP
    port: 3001 # Puerto interno del clúster para el servicio ms-nestjs-security.
    targetPort: 3001 # Puerto en el pod donde la aplicación está escuchando.
    nodePort: 32001 # Puerto externo para acceder desde fuera del clúster.
  type: NodePort # Permite el acceso externo al servicio.

