apiVersion: v1
kind: Service
metadata:
  name: ms-python-desarrollo
spec:
  selector:
    app: ms-python-desarrollo
  ports:
  - protocol: TCP
    port: 3000 # Puerto interno del clúster para el servicio ms-python.
    targetPort: 3000 # Puerto en el pod donde la aplicación está escuchando.
    nodePort: 32000 # Puerto externo para acceder desde fuera del clúster.
  type: NodePort # Permite el acceso externo al servicio.

