apiVersion: v1
kind: Service
metadata:
  name: proyecto-frontapp-desarrollo
spec:
  type: NodePort
  selector:
    app: proyecto-frontapp-desarrollo
  ports:
    - protocol: TCP
      port: 80            # Puerto interno del clúster para el servicio de frontend.
      targetPort: 80       # Puerto donde Nginx escucha en el contenedor.
      nodePort: 32003      # Puerto externo para acceder desde fuera del clúster.

