apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  labels:
    app: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      serviceAccountName: jenkins-sa
      securityContext:
        fsGroup: 1000  # El grupo que Jenkins utilizará para acceder a los archivos
      containers:
      - name: jenkins
        image: jenkins:latest
        imagePullPolicy: Never
        securityContext:
          runAsUser: 0  # Ejecutar como root para garantizar acceso completo
        ports:
        - containerPort: 8080
        - containerPort: 50000
        volumeMounts:
        - name: jenkins-home
          mountPath: /var/jenkins_home
        - name: kubeconfig
          mountPath: /root/.kube/config
          subPath: config
        - name: docker-socket
          mountPath: /var/run/docker.sock
      volumes:
      - name: jenkins-home
        persistentVolumeClaim:
          claimName: jenkins-pvc
      - name: kubeconfig
        configMap:
          name: kubeconfig-map
      - name: docker-socket
        hostPath:
          path: /var/run/docker.sock
          type: Socket







