apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  labels:
    app: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      serviceAccountName: jenkins-sa  # Asegúrate de que este service account exista y tenga permisos adecuados
      containers:
      - name: jenkins
        image: jenkins:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        - containerPort: 50000
        volumeMounts:
        - name: jenkins-home
          mountPath: /var/jenkins_home
        - name: kubeconfig
          mountPath: /root/.kube/config
          subPath: config
        - name: docker-socket
          mountPath: /var/run/docker.sock
        securityContext:
          runAsUser: 0  # Ejecutar el contenedor como root
          runAsGroup: 0  # Ejecutar el contenedor en el grupo root
      volumes:
      - name: jenkins-home
        persistentVolumeClaim:
          claimName: jenkins-pvc
      - name: kubeconfig
        configMap:
          name: kubeconfig-map
      - name: docker-socket
        hostPath:
          path: /var/run/docker.sock
          type: Socket







