apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: jenkins-sa-binding
subjects:
- kind: ServiceAccount
  name: jenkins-sa
  namespace: default  # Cambia al namespace donde está Jenkins
roleRef:
  kind: ClusterRole
  name: cluster-admin  # Puedes ajustar los permisos según sea necesario
  apiGroup: rbac.authorization.k8s.io
