apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
    - port: 50000
      targetPort: 50000
      protocol: TCP
  selector:
    app: jenkins
  type: LoadBalancer  # O ClusterIP si prefieres no exponerlo fuera del clúster
