apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
      - name: jenkins
        image: jenkins:latest
        serviceAccountName: jenkins-sa  #aqui lo deje ia esta bien?
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        - containerPort: 50000
        - containerPort: 3000
        volumeMounts:
        - name: jenkins-home
          mountPath: /var/jenkins_home
        - name: kubeconfig
          mountPath: /root/.kube/config  # Ruta en el contenedor donde estará el kubeconfig
          subPath: config
      volumes:
      - name: jenkins-home
        persistentVolumeClaim:
          claimName: jenkins-pvc
      - name: kubeconfig
        configMap:
          name: kubeconfig-map  # ConfigMap que contiene el kubeconfig


