apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
      - name: jenkins
        image: my-jenkins:latest  # Aquí se usa la imagen de Docker que ya tienes
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        - containerPort: 50000
        - containerPort: 3000
        volumeMounts:
        - name: jenkins-home
          mountPath: /var/jenkins_home
      volumes:
      - name: jenkins-home
        emptyDir: {}