apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  labels:
    app: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      serviceAccountName: jenkins-sa
      securityContext:
        fsGroup: 1000  # Grupo para acceso a archivos
      containers:
      - name: jenkins
        image: jenkins:latest
        imagePullPolicy: Never
        securityContext:
          runAsUser: 1000  # Usuario Jenkins
          runAsGroup: 1000  # Grupo Jenkins
          allowPrivilegeEscalation: false  # Deshabilitar privilegios escalados
        ports:
        - containerPort: 8080
        - containerPort: 50000
        env:
        - name: JAVA_OPTS
          value: "-Djenkins.install.runSetupWizard=false" # Evita el asistente inicial
        volumeMounts:
        - name: jenkins-home
          mountPath: /var/jenkins_home
        - name: kubeconfig
          mountPath: /root/.kube/config
          subPath: config
        - name: docker-socket
          mountPath: /var/run/docker.sock
      volumes:
      - name: jenkins-home
        persistentVolumeClaim:
          claimName: jenkins-pvc
      - name: kubeconfig
        configMap:
          name: kubeconfig-map
      - name: docker-socket
        hostPath:
          path: /var/run/docker.sock
          type: Socket








